server:
  port: ${PORT:5001}

base-url: /api

spring:
  application:
    name: taskManager

#  profiles:
#    active: ${APP_ENV:dev}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    show-sql: true
    hibernate:
        ddl-auto: create-drop


  mvc:
    hiddenmethod:
      filter:
        enabled: true

#  rollbar_token: ${ROLLBAR_TOKEN:7bffcd5a8d6d4f86929d018889fc075d}