server:
  error:
    include-stacktrace: on_param

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    url: "jdbc:h2:./taskManager"
    username: ""
    password: ""
    driverClassName: org.h2.Driver

  jpa:
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console/
      settings:
        web-allow-others: true

logging:
  level:
    root: INFO
    web: DEBUG
