server:
  port: ${PORT:5000}

base-url: /api

spring:
  application:
    name: taskManager

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    hibernate:
      #создание таблицы при запуске программы и её удаление при остановке программы
      ddl-auto: create-drop

springdoc:
  swagger-ui:
    path: /api-docs